### ISSUE TITLE
Min and Max for type number is not Working

### ISSUE THREAD

**Issue by Pondernew** [sabrio/ng2-validation-manager#2]
I tried to set a validation for phone number what i did is
          **'phone_number': 'required|minLength:10|maxLength:10|number ',**
but it does not validate min and max it just accepts any length..

**Comment by sabrio** [comment]
Sorry for the late delay, I am testing your case and everything work as it should, can you please provide more details. Btw I am adding new validation rule: count where you will be able to specify the exact number.

**Comment by sabrio** [comment]
In the 0.3.1 you can use "count" where you can specify the exact length, btw dont forget to update  the package.
